### ISSUE TITLE
code mistake

### ISSUE THREAD

**Issue by yujialele** [wqshmzh/CANet-CZSL#3]
你好，我试着跑了一下代码，发现object mlp层的维度有问题，这个是pytorch版本的问题吗？
Traceback (most recent call last):
  File "/data/yjl/CANet-CZSL-main/train.py", line 230, in <module>
    main()
  File "/data/yjl/CANet-CZSL-main/train.py", line 111, in main
    train(args, epoch, image_extractor, model, trainloader, optimizer, writer)
  File "/data/yjl/CANet-CZSL-main/train.py", line 129, in train_normal
    loss = model(data)[0]
  File "/home/zbp01/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yjl/CANet-CZSL-main/model/CANet.py", line 265, in forward
    loss, pred = self.train_forward(x)
  File "/data/yjl/CANet-CZSL-main/model/CANet.py", line 225, in train_forward
    ω_a_x = self.image_embedder_attr(x)
  File "/home/zbp01/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/yjl/CANet-CZSL-main/model/common.py", line 106, in forward
    return self.mod(x)
  File "/home/zbp01/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zbp01/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/zbp01/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zbp01/anaconda3/envs/clip/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (131072x1 and 512x512)

**Comment by wqshmzh** [comment]
由于131072=256x512，并且当args.update_image_features=False时self.image_embedder_attr(x)的x是图像特征向量，因此这是把256个长度为512的图像特征向量额外展平了而造成的错误。

**Comment by warmshiming** [comment]
你好，我在测试时也遇到了维度不一致的问题，该怎么解决呀
Traceback (most recent call last):
  File "/home1/lrHD/CANet-CZSL-main/test.py", line 134, in <module>
    main()
  File "/home1/lrHD/CANet-CZSL-main/test.py", line 87, in main
    test(image_extractor, model, testloader, evaluator, args)
  File "/home1/lrHD/CANet-CZSL-main/test.py", line 101, in test
    _, predictions = model.val_forward(data)
  File "/home1/lrHD/CANet-CZSL-main/model/CANet.py", line 171, in val_forward
    ω_a_x = self.image_embedder_attr(x)
  File "/home/lr/.conda/envs/clip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home1/lrHD/CANet-CZSL-main/model/common.py", line 44, in forward
    return self.mod(x)
  File "/home/lr/.conda/envs/clip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lr/.conda/envs/clip/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lr/.conda/envs/clip/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lr/.conda/envs/clip/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1048576x1 and 512x512)

**Comment by Vanguitar** [comment]
> 由于131072=256x512，并且当args.update_image_features=False时self.image_embedder_attr(x)的x是图像特征向量，因此这是把256个长度为512的图像特征向量额外展平了而造成的错误。

Hi Qingsheng,

I tracked the code and the x in `**self.image_embedder_attr(x)**` was (N, 512, 1, 1) as below, not was (N*512, 1):
![image](https://github.com/wqshmzh/CANet-CZSL/assets/115961895/39c4f3b9-af63-4bd3-a5d0-d7d61ae5f05b)
![image](https://github.com/wqshmzh/CANet-CZSL/assets/115961895/957b4c38-588b-45a3-9eef-7a0335b97039)

So it's confused when the x was flattened. Could you guide this? Thank you.
